# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      # -   id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
  - repo: https://github.com/thlorenz/doctoc
    rev: v2.0.0
    hooks:
      - id: doctoc
        name: "Check Table of Contents for changes"
        # verbose: true
  - repo: local
    hooks:
      - id: npm-test
        name: Run node tests
        language: system
        entry: npm run test __test__
        stages: [commit]
  - repo: local
    hooks:
      - id: npm-dockertest
        name: Run DOCKER node tests
        language: system
        stages: [push]
        exclude: .*
        always_run: true
        entry: docker build --target test .
        # verbose: true
