name: test

on:
  push:
    branches:
    - develop

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
      -
        name: Build
        run: |
          docker build --target test ./
