name: test

on:
  push:
    branches:
    - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: karmanet/dndvault
          flavor: |
            latest=true

      - name: Build test target Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          target: test
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}